### PR TITLE
Use PMDK with DDAX fixes from 1.2, 1.3, 1.4 and 1.5 branches.

### PR DESCRIPTION
**Pull request by marcinslusarz**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmdk-convert/70)

### CODE REVIEW

**Comment by lplewa** [comment]
Stable-1.3 is missing GIT_VERSION changes, next commit to this branch will change hash value

**Comment by lplewa** [comment]
Next commits to stable branches will change SHA128 values of packages (due to GIT_DESCRIBE)

**Comment by marcinslusarz** [comment]
> Next commits to stable branches will change SHA256 values of packages (due to GIT_DESCRIBE)

Nope, look closer :)

**Comment by lplewa** [comment]
> > Next commits to stable branches will change SHA256 values of packages (due to GIT_DESCRIBE)
> 
> Nope, look closer :)

Dirty hack ;)

**Pull request merged**
