### PR TITLE
Implementing tests for interrupted tranasactions for Windows

### PR DESCRIPTION
**Pull request by karolxkrzyzanowski**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmdk-convert/52)

### CODE REVIEW

**Comment by lplewa** [comment]
please read https://pmem.io/2014/09/09/git-workflow.html and apply it to your code

**Comment by karolxkrzyzanowski** [comment]
___
*[tests/helpers.cmake, line 33 at r5](https://reviewable.io/reviews/pmem/pmdk-convert/52#-LZ4nXgD-bm7jNSNZTGU:-LZ4pipf4em6TPNqa9sU:b-l6z50s) ([raw file](https://github.com/pmem/pmdk-convert/blob/b51b967b81b3f4310d9d7466c569c8338c7ab5de/tests/helpers.cmake#L33)):*
<details><summary><i>Previously, lplewa (Łukasz Plewa) wrote…</i></summary><blockquote>

why ?
</blockquote></details>

wstring paths did not read that

**Comment by karolxkrzyzanowski** [comment]
___
*[tests/helpers.cmake, line 33 at r5](https://reviewable.io/reviews/pmem/pmdk-convert/52#-LZ4nXgD-bm7jNSNZTGU:-LZ4q1WZ9dU7s8uvNSdP:b-yph328) ([raw file](https://github.com/pmem/pmdk-convert/blob/b51b967b81b3f4310d9d7466c569c8338c7ab5de/tests/helpers.cmake#L33)):*
<details><summary><i>Previously, karolxkrzyzanowski wrote…</i></summary><blockquote>

wstring paths did not read that
</blockquote></details>

i changed string to read path to wstring beacuse of parameter expected in function but this signs didnt read properly

**Comment by karolxkrzyzanowski** [comment]
___
*[tests/helpers.cmake, line 51 at r5](https://reviewable.io/reviews/pmem/pmdk-convert/52#-LZ4nbFw5IUQfAZnsr0k:-LZ4r4P03gJovY9xagWX:b-lm1ydt) ([raw file](https://github.com/pmem/pmdk-convert/blob/3037f11fbac85ac66843cc2120d5248487acf3e3/tests/helpers.cmake#L51)):*
<details><summary><i>Previously, lplewa (Łukasz Plewa) wrote…</i></summary><blockquote>

Please do not hardcode any path in the code
</blockquote></details>

Path was in PATH enviroment but it was not loaded, so i have to add the path manually

**Comment by karolxkrzyzanowski** [comment]
___
*[tests/helpers.cmake, line 56 at r5](https://reviewable.io/reviews/pmem/pmdk-convert/52#-LZ4nov_7yxHHctCnBO8:-LZ4rag56y6NhZp0yQ97:b-9xqyba) ([raw file](https://github.com/pmem/pmdk-convert/blob/3037f11fbac85ac66843cc2120d5248487acf3e3/tests/helpers.cmake#L56)):*
<details><summary><i>Previously, lplewa (Łukasz Plewa) wrote…</i></summary><blockquote>

why?
</blockquote></details>

Yeah it's not neccessary, my mystake sorry, but i combined how to run cdb command so i forgot to change this lines

**Comment by karolxkrzyzanowski** [comment]
___
*[tests/transactionW/transactionW.c, line 1 at r5](https://reviewable.io/reviews/pmem/pmdk-convert/52#-LZ4p9r03OZeEtIDhG_r:-LZ4rVf1E0k9m78zpChB:bbhu21i) ([raw file](https://github.com/pmem/pmdk-convert/blob/3037f11fbac85ac66843cc2120d5248487acf3e3/tests/transactionW/transactionW.c#L1)):*
> please do not copy entire file - please make windows support in transaction.c
So, the transaction file should be on for linux and windows, I suggested create.c and open.c files which were diffrent for windows and linux

**Comment by marcinslusarz** [comment]
Pull requests should never contain merges. If you REALLY need changes from master, then you should rebase your PR on top of master.

**Comment by lplewa** [comment]
Commits still have to be fixed,
please read https://pmem.io/2014/09/09/git-workflow.html

2 commits have the same names, there is still a merge commit in this PR, typos in commits names

**Comment by karolxkrzyzanowski** [comment]
___
*[tests/helpers.cmake, line 33 at r5](https://reviewable.io/reviews/pmem/pmdk-convert/52#-LZ4nXgD-bm7jNSNZTGU:-L_Hs3_9Bu6F_OS3csed:b-cpyt78) ([raw file](https://github.com/pmem/pmdk-convert/blob/b51b967b81b3f4310d9d7466c569c8338c7ab5de/tests/helpers.cmake#L33)):*
<details><summary><i>Previously, lplewa (Łukasz Plewa) wrote…</i></summary><blockquote>

you are removing part of the tests (we want to test support of Unicode) because your code doesn't support it)
</blockquote></details>

what should i do with this problem because in appveyor this signs doesn't read properly with pmemobj_openW function?

**Comment by karolxkrzyzanowski** [comment]
___
*[tests/helpers.cmake, line 33 at r5](https://reviewable.io/reviews/pmem/pmdk-convert/52#-LZ4nXgD-bm7jNSNZTGU:-L_I05wQ0NwAy5fg-7AO:bdw7y3) ([raw file](https://github.com/pmem/pmdk-convert/blob/b51b967b81b3f4310d9d7466c569c8338c7ab5de/tests/helpers.cmake#L33)):*
<details><summary><i>Previously, karolxkrzyzanowski wrote…</i></summary><blockquote>

what should i do with this problem because in appveyor this signs doesn't read properly with pmemobj_openW function?
</blockquote></details>

Sorry, my bad i corrected the parameter of function everything is ok

**Comment by karolxkrzyzanowski** [comment]
___
*[tests/helpers.cmake, line 51 at r5](https://reviewable.io/reviews/pmem/pmdk-convert/52#-LZ4nbFw5IUQfAZnsr0k:-L_IAJ8u-2PakpKANOHg:bd6ns87) ([raw file](https://github.com/pmem/pmdk-convert/blob/f3f723e50e52aea03f68aceeceaf02e0ad7c30b9/tests/helpers.cmake#L51)):*
<details><summary><i>Previously, lplewa (Łukasz Plewa) wrote…</i></summary><blockquote>

This is not acceptable to hardcore ANY path in the code.

Please add checker if cdb is in the path and skip the test if not
(ofcourse add it to path on appveyor) 

</blockquote></details>

Added checking that cdb file is existing if not the tests are not executing.

**Comment by karolxkrzyzanowski** [comment]
___
*[tests/helpers.cmake, line 241 at r15](https://reviewable.io/reviews/pmem/pmdk-convert/52#-L_IAXSPCkFQrnq9swvt:-L_IAXSPCkFQrnq9swvu:b-chans) ([raw file](https://github.com/pmem/pmdk-convert/blob/1d59dc51cecafccd8258d629a314bb8d03484345/tests/helpers.cmake#L241)):*
> ```CMake
> 					${CMAKE_CURRENT_BINARY_DIR}/transactionW/${CONFIG}/transaction_${next_bin_version}
> 					${DIR}/pool${curr_bin_version}c vc ${curr_scenario})
> 			endif()
> ```

Checking cdb existing to execute tests.

**Comment by karolxkrzyzanowski** [comment]
___
*[tests/transaction.c, line 593 at r12](https://reviewable.io/reviews/pmem/pmdk-convert/52#-L_HbmaE44-eXHXR6dGa:-L_IAn-YD_28cbS7QM_M:b-65yntb) ([raw file](https://github.com/pmem/pmdk-convert/blob/9bc77faac33727772db259517c347f6cbd565ab9/tests/transaction.c#L593)):*
<details><summary><i>Previously, lplewa (Łukasz Plewa) wrote…</i></summary><blockquote>

please use 	
wchar_t **wargv = CommandLineToArgvW(GetCommandLineW(), &argc);

and call pmemobj_openW
</blockquote></details>

Added as You mention before.

**Comment by karolxkrzyzanowski** [comment]
___
*[appveyor.yml, line 12 at r15](https://reviewable.io/reviews/pmem/pmdk-convert/52#-L_IAyLW-lxTPogXcjSE:-L_IAyLW-lxTPogXcjSF:bfytney) ([raw file](https://github.com/pmem/pmdk-convert/blob/1d59dc51cecafccd8258d629a314bb8d03484345/appveyor.yml#L12)):*
> ```YAML
> - vcpkg install pmdk:x64-windows
> - vcpkg integrate install
> - set PATH=C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\cdb.exe;%PATH%
> ```

Added cdb local file to PATH as You asked

**Comment by karolxkrzyzanowski** [comment]
___
*[appveyor.yml, line 29 at r16](https://reviewable.io/reviews/pmem/pmdk-convert/52#-L_qYJVH5tG2SVnF6a8g:-L_qYJVH5tG2SVnF6a8h:b2lpbp7) ([raw file](https://github.com/pmem/pmdk-convert/blob/7f9f50a3844e2336a11a228de7abc1913518f566/appveyor.yml#L29)):*
> ```YAML
>         -DCMAKE_SYSTEM_VERSION="10.0.26624"
>         -DTESTS_USE_FORCED_PMEM=ON 
>         -DCDB_PATH:PATH="C:\Program Files (x86)\Windows Kits\10\Debuggers\x64"
> ```

added path to appveyor

**Comment by karolxkrzyzanowski** [comment]
___
*[tests/CMakeLists.txt, line 49 at r16](https://reviewable.io/reviews/pmem/pmdk-convert/52#-L_qYSFy3BvnQOFa8oPR:-L_qYSFy3BvnQOFa8oPS:b-rb2qth) ([raw file](https://github.com/pmem/pmdk-convert/blob/7f9f50a3844e2336a11a228de7abc1913518f566/tests/CMakeLists.txt#L49)):*
> ```CMake
> 	-DTESTS_USE_FORCED_PMEM=${TESTS_USE_FORCED_PMEM}
> 	-DDEVICE_DAX_PATHS=${DEVICE_DAX_PATHS}
> 	-DCDB_PATH=${CDB_PATH})
> ```

Set path as empty string default

**Comment by karolxkrzyzanowski** [comment]
___
*[tests/helpers.cmake, line 49 at r16](https://reviewable.io/reviews/pmem/pmdk-convert/52#-L_qYYYxCGVc7kuo61f9:-L_qYYYxCGVc7kuo61fA:b-18swez) ([raw file](https://github.com/pmem/pmdk-convert/blob/7f9f50a3844e2336a11a228de7abc1913518f566/tests/helpers.cmake#L49)):*
> ```CMake
> 	if(CDB_PATH)
> 		find_program(CDB_EXE cdb.exe PATH CDB_PATH)
> 	endif()
> ```

finding cdb

**Comment by karolxkrzyzanowski** [comment]
___
*[tests/helpers.cmake, line 113 at r17](https://reviewable.io/reviews/pmem/pmdk-convert/52#-L_q_znW7Ar6MPak9Irc:-L_q_znW7Ar6MPak9Ird:b-7pw730) ([raw file](https://github.com/pmem/pmdk-convert/blob/310e2247d468523fe9b3116c05d8701201132540/tests/helpers.cmake#L113)):*
> ```CMake
> 	unset(CDB_EXE)
> endif()
> endfunction()
> ```

Finding cdb if exists

**Comment by karolxkrzyzanowski** [comment]
___
*[tests/transactionW/CMakeLists.txt, line 34 at r18](https://reviewable.io/reviews/pmem/pmdk-convert/52#-L_wYkav1QeeiGjvyjyz:-LaLKLpc6OKTjupmQVOp:bh0m6tm) ([raw file](https://github.com/pmem/pmdk-convert/blob/6e6aa01b85246b47974f283856f2dbb2e11b3c07/tests/transactionW/CMakeLists.txt#L34)):*
<details><summary><i>Previously, Greg091 (Grzegorz Brzeziński) wrote…</i></summary><blockquote>

First of all, convert supports Windows from 1.4 version, so versions below are not needed. Second thing, you double the same code. Please use if(Wind32) statement instead of writing the same twice.
</blockquote></details>

I tried move the flag to tests/CmakeLists.txt but it turn on to every project which tests/CMakeLists.txt file contains and this make a lot of errors in project, even with WIN32 condition and turning on the flag and after creating needed project turn off, but then all projects in tests/CMakeLists.txt file had the flag off so transactions had errors becuase of not turning the flag. Only resolve for this was separating the transaction from the rest, of course i must doubling code but for now i dont see any other resolve to this.

**Comment by lukaszstolarczuk** [comment]
@karolxkrzyzanowski, please change the PR title to something more like commit title - it is an open source repo and reference to our internal tools is not the best choice ;) We need to know (based on PR title) what is going to be changed and it should lack the obvious information like repo name and "pool request" part (FYI, it is: pull request)

**Comment by karolxkrzyzanowski** [comment]
___
*[appveyor.yml, line 1 at r18](https://reviewable.io/reviews/pmem/pmdk-convert/52#-La-kFrTDciG4J2h3EHu:-LaQjiXuD8LgBpl4JdJz:b-896fix) ([raw file](https://github.com/pmem/pmdk-convert/blob/6e6aa01b85246b47974f283856f2dbb2e11b3c07/appveyor.yml#L1)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

in commit message you can omit last part: "Set license date to build in travis." - it's not providing a meaningful info, since all PR should update the license date
</blockquote></details>

Done.

**Comment by karolxkrzyzanowski** [comment]
___
*[appveyor.yml, line 29 at r16](https://reviewable.io/reviews/pmem/pmdk-convert/52#-L_qYJVH5tG2SVnF6a8g:-LaQjnvJ6g__RaCkZqeU:biuh0i7) ([raw file](https://github.com/pmem/pmdk-convert/blob/7f9f50a3844e2336a11a228de7abc1913518f566/appveyor.yml#L29)):*
<details><summary><i>Previously, lplewa (Łukasz Plewa) wrote…</i></summary><blockquote>

Do we need this? as you set PATH above this should be not needed
</blockquote></details>

I removed PATH variable from appveyor, because when we run cmake command to create project it's imposible for me to set PATH with cdb location variable, so i decided to remove PATH variable but if You have any idea how to do it write to me or apply to this comment

**Comment by karolxkrzyzanowski** [comment]
___
*[tests/CMakeLists.txt, line 584 at r18](https://reviewable.io/reviews/pmem/pmdk-convert/52#-L_wHFn19hFpury1QgXN:-LaQkZnN04mjaeXhaZuO:b-896fix) ([raw file](https://github.com/pmem/pmdk-convert/blob/6e6aa01b85246b47974f283856f2dbb2e11b3c07/tests/CMakeLists.txt#L584)):*
<details><summary><i>Previously, Greg091 (Grzegorz Brzeziński) wrote…</i></summary><blockquote>

The clean_pool is added twice (on Linux and Windows). Please add clean_pool once, outside 'if' condition.
</blockquote></details>

Done.

**Comment by karolxkrzyzanowski** [comment]
___
*[tests/CMakeLists.txt, line 590 at r18](https://reviewable.io/reviews/pmem/pmdk-convert/52#-L_wF_sp4QCrHiyC1EMs:-LaQkdHt3pLWrwMrnCbL:b-896fix) ([raw file](https://github.com/pmem/pmdk-convert/blob/6e6aa01b85246b47974f283856f2dbb2e11b3c07/tests/CMakeLists.txt#L590)):*
<details><summary><i>Previously, Greg091 (Grzegorz Brzeziński) wrote…</i></summary><blockquote>

On release build please write the message like 'tx_intr_pool_regfile_win_SKIP_BECAUSE_OF_RELEASE_BUILD_TYPE'. Please write messages like messages of devdax tests on Linux. In case of cdb is unavailable you should give another message: 'tx_intr_pool_regfile_win_SKIP_BECAUSE_OF_CDB_IS_NOT_INSTALLED'.
</blockquote></details>

Done.

**Comment by karolxkrzyzanowski** [comment]
___
*[tests/helpers.cmake, line 38 at r18](https://reviewable.io/reviews/pmem/pmdk-convert/52#-L_wLZn79pzusSuuxSNA:-LaQkfDkCNjGb4cc4AFq:b-896fix) ([raw file](https://github.com/pmem/pmdk-convert/blob/6e6aa01b85246b47974f283856f2dbb2e11b3c07/tests/helpers.cmake#L38)):*
<details><summary><i>Previously, Greg091 (Grzegorz Brzeziński) wrote…</i></summary><blockquote>

please remove space
</blockquote></details>

Done.

**Comment by karolxkrzyzanowski** [comment]
___
*[tests/helpers.cmake, line 109 at r18](https://reviewable.io/reviews/pmem/pmdk-convert/52#-L_wOc0KES_Z9mNyWmQj:-LaQkm811YKaj2Y45pza:b-8u7x8b) ([raw file](https://github.com/pmem/pmdk-convert/blob/6e6aa01b85246b47974f283856f2dbb2e11b3c07/tests/helpers.cmake#L109)):*
<details><summary><i>Previously, Greg091 (Grzegorz Brzeziński) wrote…</i></summary><blockquote>

please check if operation succeeded
</blockquote></details>

I moved cdb function to tests/CmakeList.txt and there i added a condition if that path really exist

**Comment by karolxkrzyzanowski** [comment]
___
*[tests/helpers.cmake, line 106 at r18](https://reviewable.io/reviews/pmem/pmdk-convert/52#-L_wR0KkBql2Rg4nTv65:-LaQkzZ9-wA-fvZHmBij:b-8vuizc) ([raw file](https://github.com/pmem/pmdk-convert/blob/6e6aa01b85246b47974f283856f2dbb2e11b3c07/tests/helpers.cmake#L106)):*
<details><summary><i>Previously, Greg091 (Grzegorz Brzeziński) wrote…</i></summary><blockquote>

Please add a short description of 'set_cdb_executable' function
</blockquote></details>

added but moved to tests/cmakeLists.txt

**Comment by karolxkrzyzanowski** [comment]
___
*[tests/helpers.cmake, line 128 at r18](https://reviewable.io/reviews/pmem/pmdk-convert/52#-L_wRrbw1gqeAxtxkmx2:-LaQl73B9U8ahpi-pOl6:b-896fix) ([raw file](https://github.com/pmem/pmdk-convert/blob/6e6aa01b85246b47974f283856f2dbb2e11b3c07/tests/helpers.cmake#L128)):*
<details><summary><i>Previously, Greg091 (Grzegorz Brzeziński) wrote…</i></summary><blockquote>

Can you execute both cdb operation without 'if' condition at the same time? Then you can delete MODE variable.
</blockquote></details>

Done.

**Comment by karolxkrzyzanowski** [comment]
___
*[tests/helpers.cmake, line 242 at r18](https://reviewable.io/reviews/pmem/pmdk-convert/52#-L_wTOkK0R9bACNVLse5:-LaQlAoOEKq2d0TRxgEF:b-896fix) ([raw file](https://github.com/pmem/pmdk-convert/blob/6e6aa01b85246b47974f283856f2dbb2e11b3c07/tests/helpers.cmake#L242)):*
<details><summary><i>Previously, Greg091 (Grzegorz Brzeziński) wrote…</i></summary><blockquote>

You should skip test in CMakeList file, like in devdax tests on Linux.
</blockquote></details>

Done.

**Comment by karolxkrzyzanowski** [comment]
___
*[tests/helpers.cmake, line 225 at r18](https://reviewable.io/reviews/pmem/pmdk-convert/52#-L_wTd5s3QG21DaySYNM:-LaQlCZD69e93ptcN_e5:b-896fix) ([raw file](https://github.com/pmem/pmdk-convert/blob/6e6aa01b85246b47974f283856f2dbb2e11b3c07/tests/helpers.cmake#L225)):*
<details><summary><i>Previously, Greg091 (Grzegorz Brzeziński) wrote…</i></summary><blockquote>

Please check if cdb is available in CMakeList file.
</blockquote></details>

Done.

**Comment by karolxkrzyzanowski** [comment]
___
*[tests/transaction.c, line 605 at r18](https://reviewable.io/reviews/pmem/pmdk-convert/52#-L_wVr9VALENkQ8Y2_f0:-LaQlNIl2K28sorVAvxZ:b-896fix) ([raw file](https://github.com/pmem/pmdk-convert/blob/6e6aa01b85246b47974f283856f2dbb2e11b3c07/tests/transaction.c#L605)):*
<details><summary><i>Previously, Greg091 (Grzegorz Brzeziński) wrote…</i></summary><blockquote>

Please Shoot larger indentation like below. The code should be consistent.
</blockquote></details>

Done.

**Comment by karolxkrzyzanowski** [comment]
___
*[tests/tx_intr_pool_regfile_win.cmake, line 31 at r18](https://reviewable.io/reviews/pmem/pmdk-convert/52#-L_w_Jba2ym6tCfH0Zx5:-LaQlR3o3EBOeDdnJFw0:b-896fix) ([raw file](https://github.com/pmem/pmdk-convert/blob/6e6aa01b85246b47974f283856f2dbb2e11b3c07/tests/tx_intr_pool_regfile_win.cmake#L31)):*
<details><summary><i>Previously, Greg091 (Grzegorz Brzeziński) wrote…</i></summary><blockquote>

Please merge tests tx_intr_pool_regfile_win.cmake tx_intr_pool_regfile.cmake into one file. Please use statement 'if(Win32)'.
</blockquote></details>

Done.

**Comment by karolxkrzyzanowski** [comment]
___
*[tests/tx_intr_poolset_local_2regfiles_win.cmake, line 32 at r18](https://reviewable.io/reviews/pmem/pmdk-convert/52#-L_w_hAfCs2wn4h0-Pvc:-LaQlTDL5nxRvEwpLzZg:b-896fix) ([raw file](https://github.com/pmem/pmdk-convert/blob/6e6aa01b85246b47974f283856f2dbb2e11b3c07/tests/tx_intr_poolset_local_2regfiles_win.cmake#L32)):*
<details><summary><i>Previously, Greg091 (Grzegorz Brzeziński) wrote…</i></summary><blockquote>

Please merge tests tx_intr_poolset_local_2regfiles_win.cmake tx_intr_poolset_local_2regfiles.cmake into one file. Please use statement 'if(Win32)'.
</blockquote></details>

Done.

**Comment by karolxkrzyzanowski** [comment]
___
*[tests/tx_intr_poolset_local_regfile_rep_regfile_win.cmake, line 32 at r18](https://reviewable.io/reviews/pmem/pmdk-convert/52#-L_w_tjm-EZINugsRQoN:-LaQlp8e1uoPGECvG9VQ:b-896fix) ([raw file](https://github.com/pmem/pmdk-convert/blob/6e6aa01b85246b47974f283856f2dbb2e11b3c07/tests/tx_intr_poolset_local_regfile_rep_regfile_win.cmake#L32)):*
<details><summary><i>Previously, Greg091 (Grzegorz Brzeziński) wrote…</i></summary><blockquote>

Please merge tests tx_intr_poolset_local_regfile_rep_regfile_win.cmake tx_intr_poolset_local_regfile_rep_regfile.cmake into one file. Please use statement 'if(Win32)'.
</blockquote></details>

Done.

**Comment by karolxkrzyzanowski** [comment]
___
*[tests/transactionW/CMakeLists.txt, line 34 at r18](https://reviewable.io/reviews/pmem/pmdk-convert/52#-L_wYkav1QeeiGjvyjyz:-LaQlvqN57niEPVfr3EX:b-ovn798) ([raw file](https://github.com/pmem/pmdk-convert/blob/6e6aa01b85246b47974f283856f2dbb2e11b3c07/tests/transactionW/CMakeLists.txt#L34)):*
<details><summary><i>Previously, Greg091 (Grzegorz Brzeziński) wrote…</i></summary><blockquote>

So if you have errors, please resolve these issues :) Hint: You have to compile as C++ code only two targets: transaction_14 and transaction_15.
</blockquote></details>

How to resolve that if the projects errors which are directly connected with changing flags? I can put the flag in tests/cmakeList.txt but it no matter where you put the flag if is setup, then all of the projects has it as its own property. For example in tests/cmakeList are creating projects like pmemspoil, pmempool-convert which are earlier runs and even if i put the flag after them, they has flag the same as i set in tests/CMakeLists so i can't put this flag in this file even if i wanted.

**Comment by lplewa** [comment]
Please rebase to the master

**Comment by marcinslusarz** [comment]
___
*[tests/CMakeLists.txt, line 536 at r22](https://reviewable.io/reviews/pmem/pmdk-convert/52#-LbNPH-s5Xqzl2GykkC9:-LbOedl18ll8YYLjJLR9:ba6a16d) ([raw file](https://github.com/pmem/pmdk-convert/blob/9ac80cffa1268dc4979dee67cecaa4458f83dd3a/tests/CMakeLists.txt#L536)):*
<details><summary><i>Previously, karolxkrzyzanowski wrote…</i></summary><blockquote>

i tried put your command, but i get error that unresolved external symbol __imp_CommandLineToArgvW referenced in function main, so i found on internet was solution which is to set CMAKE_USER_MAKE_RULES_OVERRIDE but it also doesn't work for me. When I tried to create cmake project i have errors that all CXX flags are not set. I don't know how to resolve all these problems. Because all flags are set for C project in main CMakeTLists.txt and the rest CmakeLists.txt inherit flags from it.
</blockquote></details>

I don't know how the heck you've managed to get to this part, because just running "cmake" on your code with this change generate pretty obvious error messages.

Solution: change "project(pmdk-convert C)" to "project(pmdk-convert C CXX)" in the main CMakeLists.txt.

**Pull request merged**
